// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awesomeProject1/ent/chat"
	"awesomeProject1/ent/message"
	"awesomeProject1/ent/predicate"
	"awesomeProject1/ent/professor"
	"awesomeProject1/ent/student"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetText sets the "text" field.
func (mu *MessageUpdate) SetText(s string) *MessageUpdate {
	mu.mutation.SetText(s)
	return mu
}

// SetNillableText sets the "text" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableText(s *string) *MessageUpdate {
	if s != nil {
		mu.SetText(*s)
	}
	return mu
}

// SetTimestamp sets the "timestamp" field.
func (mu *MessageUpdate) SetTimestamp(t time.Time) *MessageUpdate {
	mu.mutation.SetTimestamp(t)
	return mu
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableTimestamp(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetTimestamp(*t)
	}
	return mu
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (mu *MessageUpdate) SetChatID(id int) *MessageUpdate {
	mu.mutation.SetChatID(id)
	return mu
}

// SetNillableChatID sets the "chat" edge to the Chat entity by ID if the given value is not nil.
func (mu *MessageUpdate) SetNillableChatID(id *int) *MessageUpdate {
	if id != nil {
		mu = mu.SetChatID(*id)
	}
	return mu
}

// SetChat sets the "chat" edge to the Chat entity.
func (mu *MessageUpdate) SetChat(c *Chat) *MessageUpdate {
	return mu.SetChatID(c.ID)
}

// SetSenderID sets the "sender" edge to the Student entity by ID.
func (mu *MessageUpdate) SetSenderID(id int) *MessageUpdate {
	mu.mutation.SetSenderID(id)
	return mu
}

// SetNillableSenderID sets the "sender" edge to the Student entity by ID if the given value is not nil.
func (mu *MessageUpdate) SetNillableSenderID(id *int) *MessageUpdate {
	if id != nil {
		mu = mu.SetSenderID(*id)
	}
	return mu
}

// SetSender sets the "sender" edge to the Student entity.
func (mu *MessageUpdate) SetSender(s *Student) *MessageUpdate {
	return mu.SetSenderID(s.ID)
}

// SetReceiverID sets the "receiver" edge to the Professor entity by ID.
func (mu *MessageUpdate) SetReceiverID(id int) *MessageUpdate {
	mu.mutation.SetReceiverID(id)
	return mu
}

// SetNillableReceiverID sets the "receiver" edge to the Professor entity by ID if the given value is not nil.
func (mu *MessageUpdate) SetNillableReceiverID(id *int) *MessageUpdate {
	if id != nil {
		mu = mu.SetReceiverID(*id)
	}
	return mu
}

// SetReceiver sets the "receiver" edge to the Professor entity.
func (mu *MessageUpdate) SetReceiver(p *Professor) *MessageUpdate {
	return mu.SetReceiverID(p.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// ClearChat clears the "chat" edge to the Chat entity.
func (mu *MessageUpdate) ClearChat() *MessageUpdate {
	mu.mutation.ClearChat()
	return mu
}

// ClearSender clears the "sender" edge to the Student entity.
func (mu *MessageUpdate) ClearSender() *MessageUpdate {
	mu.mutation.ClearSender()
	return mu
}

// ClearReceiver clears the "receiver" edge to the Professor entity.
func (mu *MessageUpdate) ClearReceiver() *MessageUpdate {
	mu.mutation.ClearReceiver()
	return mu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MessageUpdate) check() error {
	if v, ok := mu.mutation.Text(); ok {
		if err := message.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Message.text": %w`, err)}
		}
	}
	return nil
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Text(); ok {
		_spec.SetField(message.FieldText, field.TypeString, value)
	}
	if value, ok := mu.mutation.Timestamp(); ok {
		_spec.SetField(message.FieldTimestamp, field.TypeTime, value)
	}
	if mu.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   message.SenderTable,
			Columns: []string{message.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   message.SenderTable,
			Columns: []string{message.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.ReceiverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   message.ReceiverTable,
			Columns: []string{message.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(professor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.ReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   message.ReceiverTable,
			Columns: []string{message.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(professor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetText sets the "text" field.
func (muo *MessageUpdateOne) SetText(s string) *MessageUpdateOne {
	muo.mutation.SetText(s)
	return muo
}

// SetNillableText sets the "text" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableText(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetText(*s)
	}
	return muo
}

// SetTimestamp sets the "timestamp" field.
func (muo *MessageUpdateOne) SetTimestamp(t time.Time) *MessageUpdateOne {
	muo.mutation.SetTimestamp(t)
	return muo
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableTimestamp(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetTimestamp(*t)
	}
	return muo
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (muo *MessageUpdateOne) SetChatID(id int) *MessageUpdateOne {
	muo.mutation.SetChatID(id)
	return muo
}

// SetNillableChatID sets the "chat" edge to the Chat entity by ID if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableChatID(id *int) *MessageUpdateOne {
	if id != nil {
		muo = muo.SetChatID(*id)
	}
	return muo
}

// SetChat sets the "chat" edge to the Chat entity.
func (muo *MessageUpdateOne) SetChat(c *Chat) *MessageUpdateOne {
	return muo.SetChatID(c.ID)
}

// SetSenderID sets the "sender" edge to the Student entity by ID.
func (muo *MessageUpdateOne) SetSenderID(id int) *MessageUpdateOne {
	muo.mutation.SetSenderID(id)
	return muo
}

// SetNillableSenderID sets the "sender" edge to the Student entity by ID if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableSenderID(id *int) *MessageUpdateOne {
	if id != nil {
		muo = muo.SetSenderID(*id)
	}
	return muo
}

// SetSender sets the "sender" edge to the Student entity.
func (muo *MessageUpdateOne) SetSender(s *Student) *MessageUpdateOne {
	return muo.SetSenderID(s.ID)
}

// SetReceiverID sets the "receiver" edge to the Professor entity by ID.
func (muo *MessageUpdateOne) SetReceiverID(id int) *MessageUpdateOne {
	muo.mutation.SetReceiverID(id)
	return muo
}

// SetNillableReceiverID sets the "receiver" edge to the Professor entity by ID if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableReceiverID(id *int) *MessageUpdateOne {
	if id != nil {
		muo = muo.SetReceiverID(*id)
	}
	return muo
}

// SetReceiver sets the "receiver" edge to the Professor entity.
func (muo *MessageUpdateOne) SetReceiver(p *Professor) *MessageUpdateOne {
	return muo.SetReceiverID(p.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// ClearChat clears the "chat" edge to the Chat entity.
func (muo *MessageUpdateOne) ClearChat() *MessageUpdateOne {
	muo.mutation.ClearChat()
	return muo
}

// ClearSender clears the "sender" edge to the Student entity.
func (muo *MessageUpdateOne) ClearSender() *MessageUpdateOne {
	muo.mutation.ClearSender()
	return muo
}

// ClearReceiver clears the "receiver" edge to the Professor entity.
func (muo *MessageUpdateOne) ClearReceiver() *MessageUpdateOne {
	muo.mutation.ClearReceiver()
	return muo
}

// Where appends a list predicates to the MessageUpdate builder.
func (muo *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MessageUpdateOne) check() error {
	if v, ok := muo.mutation.Text(); ok {
		if err := message.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Message.text": %w`, err)}
		}
	}
	return nil
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Text(); ok {
		_spec.SetField(message.FieldText, field.TypeString, value)
	}
	if value, ok := muo.mutation.Timestamp(); ok {
		_spec.SetField(message.FieldTimestamp, field.TypeTime, value)
	}
	if muo.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   message.SenderTable,
			Columns: []string{message.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   message.SenderTable,
			Columns: []string{message.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.ReceiverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   message.ReceiverTable,
			Columns: []string{message.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(professor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.ReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   message.ReceiverTable,
			Columns: []string{message.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(professor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
