// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awesomeProject1/ent/chat"
	"awesomeProject1/ent/message"
	"awesomeProject1/ent/predicate"
	"awesomeProject1/ent/professor"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfessorUpdate is the builder for updating Professor entities.
type ProfessorUpdate struct {
	config
	hooks    []Hook
	mutation *ProfessorMutation
}

// Where appends a list predicates to the ProfessorUpdate builder.
func (pu *ProfessorUpdate) Where(ps ...predicate.Professor) *ProfessorUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetName sets the "name" field.
func (pu *ProfessorUpdate) SetName(s string) *ProfessorUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *ProfessorUpdate) SetNillableName(s *string) *ProfessorUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// SetHireDate sets the "hire_date" field.
func (pu *ProfessorUpdate) SetHireDate(t time.Time) *ProfessorUpdate {
	pu.mutation.SetHireDate(t)
	return pu
}

// SetNillableHireDate sets the "hire_date" field if the given value is not nil.
func (pu *ProfessorUpdate) SetNillableHireDate(t *time.Time) *ProfessorUpdate {
	if t != nil {
		pu.SetHireDate(*t)
	}
	return pu
}

// SetPassword sets the "password" field.
func (pu *ProfessorUpdate) SetPassword(s string) *ProfessorUpdate {
	pu.mutation.SetPassword(s)
	return pu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (pu *ProfessorUpdate) SetNillablePassword(s *string) *ProfessorUpdate {
	if s != nil {
		pu.SetPassword(*s)
	}
	return pu
}

// SetChatsID sets the "chats" edge to the Chat entity by ID.
func (pu *ProfessorUpdate) SetChatsID(id int) *ProfessorUpdate {
	pu.mutation.SetChatsID(id)
	return pu
}

// SetNillableChatsID sets the "chats" edge to the Chat entity by ID if the given value is not nil.
func (pu *ProfessorUpdate) SetNillableChatsID(id *int) *ProfessorUpdate {
	if id != nil {
		pu = pu.SetChatsID(*id)
	}
	return pu
}

// SetChats sets the "chats" edge to the Chat entity.
func (pu *ProfessorUpdate) SetChats(c *Chat) *ProfessorUpdate {
	return pu.SetChatsID(c.ID)
}

// SetReceivedMessagesID sets the "received_messages" edge to the Message entity by ID.
func (pu *ProfessorUpdate) SetReceivedMessagesID(id int) *ProfessorUpdate {
	pu.mutation.SetReceivedMessagesID(id)
	return pu
}

// SetNillableReceivedMessagesID sets the "received_messages" edge to the Message entity by ID if the given value is not nil.
func (pu *ProfessorUpdate) SetNillableReceivedMessagesID(id *int) *ProfessorUpdate {
	if id != nil {
		pu = pu.SetReceivedMessagesID(*id)
	}
	return pu
}

// SetReceivedMessages sets the "received_messages" edge to the Message entity.
func (pu *ProfessorUpdate) SetReceivedMessages(m *Message) *ProfessorUpdate {
	return pu.SetReceivedMessagesID(m.ID)
}

// Mutation returns the ProfessorMutation object of the builder.
func (pu *ProfessorUpdate) Mutation() *ProfessorMutation {
	return pu.mutation
}

// ClearChats clears the "chats" edge to the Chat entity.
func (pu *ProfessorUpdate) ClearChats() *ProfessorUpdate {
	pu.mutation.ClearChats()
	return pu
}

// ClearReceivedMessages clears the "received_messages" edge to the Message entity.
func (pu *ProfessorUpdate) ClearReceivedMessages() *ProfessorUpdate {
	pu.mutation.ClearReceivedMessages()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProfessorUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProfessorUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProfessorUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProfessorUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProfessorUpdate) check() error {
	if v, ok := pu.mutation.Name(); ok {
		if err := professor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Professor.name": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Password(); ok {
		if err := professor.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Professor.password": %w`, err)}
		}
	}
	return nil
}

func (pu *ProfessorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(professor.Table, professor.Columns, sqlgraph.NewFieldSpec(professor.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(professor.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.HireDate(); ok {
		_spec.SetField(professor.FieldHireDate, field.TypeTime, value)
	}
	if value, ok := pu.mutation.Password(); ok {
		_spec.SetField(professor.FieldPassword, field.TypeString, value)
	}
	if pu.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   professor.ChatsTable,
			Columns: []string{professor.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.ChatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   professor.ChatsTable,
			Columns: []string{professor.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.ReceivedMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   professor.ReceivedMessagesTable,
			Columns: []string{professor.ReceivedMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.ReceivedMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   professor.ReceivedMessagesTable,
			Columns: []string{professor.ReceivedMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{professor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProfessorUpdateOne is the builder for updating a single Professor entity.
type ProfessorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfessorMutation
}

// SetName sets the "name" field.
func (puo *ProfessorUpdateOne) SetName(s string) *ProfessorUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *ProfessorUpdateOne) SetNillableName(s *string) *ProfessorUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// SetHireDate sets the "hire_date" field.
func (puo *ProfessorUpdateOne) SetHireDate(t time.Time) *ProfessorUpdateOne {
	puo.mutation.SetHireDate(t)
	return puo
}

// SetNillableHireDate sets the "hire_date" field if the given value is not nil.
func (puo *ProfessorUpdateOne) SetNillableHireDate(t *time.Time) *ProfessorUpdateOne {
	if t != nil {
		puo.SetHireDate(*t)
	}
	return puo
}

// SetPassword sets the "password" field.
func (puo *ProfessorUpdateOne) SetPassword(s string) *ProfessorUpdateOne {
	puo.mutation.SetPassword(s)
	return puo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (puo *ProfessorUpdateOne) SetNillablePassword(s *string) *ProfessorUpdateOne {
	if s != nil {
		puo.SetPassword(*s)
	}
	return puo
}

// SetChatsID sets the "chats" edge to the Chat entity by ID.
func (puo *ProfessorUpdateOne) SetChatsID(id int) *ProfessorUpdateOne {
	puo.mutation.SetChatsID(id)
	return puo
}

// SetNillableChatsID sets the "chats" edge to the Chat entity by ID if the given value is not nil.
func (puo *ProfessorUpdateOne) SetNillableChatsID(id *int) *ProfessorUpdateOne {
	if id != nil {
		puo = puo.SetChatsID(*id)
	}
	return puo
}

// SetChats sets the "chats" edge to the Chat entity.
func (puo *ProfessorUpdateOne) SetChats(c *Chat) *ProfessorUpdateOne {
	return puo.SetChatsID(c.ID)
}

// SetReceivedMessagesID sets the "received_messages" edge to the Message entity by ID.
func (puo *ProfessorUpdateOne) SetReceivedMessagesID(id int) *ProfessorUpdateOne {
	puo.mutation.SetReceivedMessagesID(id)
	return puo
}

// SetNillableReceivedMessagesID sets the "received_messages" edge to the Message entity by ID if the given value is not nil.
func (puo *ProfessorUpdateOne) SetNillableReceivedMessagesID(id *int) *ProfessorUpdateOne {
	if id != nil {
		puo = puo.SetReceivedMessagesID(*id)
	}
	return puo
}

// SetReceivedMessages sets the "received_messages" edge to the Message entity.
func (puo *ProfessorUpdateOne) SetReceivedMessages(m *Message) *ProfessorUpdateOne {
	return puo.SetReceivedMessagesID(m.ID)
}

// Mutation returns the ProfessorMutation object of the builder.
func (puo *ProfessorUpdateOne) Mutation() *ProfessorMutation {
	return puo.mutation
}

// ClearChats clears the "chats" edge to the Chat entity.
func (puo *ProfessorUpdateOne) ClearChats() *ProfessorUpdateOne {
	puo.mutation.ClearChats()
	return puo
}

// ClearReceivedMessages clears the "received_messages" edge to the Message entity.
func (puo *ProfessorUpdateOne) ClearReceivedMessages() *ProfessorUpdateOne {
	puo.mutation.ClearReceivedMessages()
	return puo
}

// Where appends a list predicates to the ProfessorUpdate builder.
func (puo *ProfessorUpdateOne) Where(ps ...predicate.Professor) *ProfessorUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProfessorUpdateOne) Select(field string, fields ...string) *ProfessorUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Professor entity.
func (puo *ProfessorUpdateOne) Save(ctx context.Context) (*Professor, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProfessorUpdateOne) SaveX(ctx context.Context) *Professor {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProfessorUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProfessorUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProfessorUpdateOne) check() error {
	if v, ok := puo.mutation.Name(); ok {
		if err := professor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Professor.name": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Password(); ok {
		if err := professor.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Professor.password": %w`, err)}
		}
	}
	return nil
}

func (puo *ProfessorUpdateOne) sqlSave(ctx context.Context) (_node *Professor, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(professor.Table, professor.Columns, sqlgraph.NewFieldSpec(professor.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Professor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, professor.FieldID)
		for _, f := range fields {
			if !professor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != professor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(professor.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.HireDate(); ok {
		_spec.SetField(professor.FieldHireDate, field.TypeTime, value)
	}
	if value, ok := puo.mutation.Password(); ok {
		_spec.SetField(professor.FieldPassword, field.TypeString, value)
	}
	if puo.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   professor.ChatsTable,
			Columns: []string{professor.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.ChatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   professor.ChatsTable,
			Columns: []string{professor.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.ReceivedMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   professor.ReceivedMessagesTable,
			Columns: []string{professor.ReceivedMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.ReceivedMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   professor.ReceivedMessagesTable,
			Columns: []string{professor.ReceivedMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Professor{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{professor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
