// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awesomeProject1/ent/message"
	"awesomeProject1/ent/professor"
	"awesomeProject1/ent/schema"
	"awesomeProject1/ent/student"
	"awesomeProject1/ent/university"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescText is the schema descriptor for text field.
	messageDescText := messageFields[0].Descriptor()
	// message.TextValidator is a validator for the "text" field. It is called by the builders before save.
	message.TextValidator = messageDescText.Validators[0].(func(string) error)
	// messageDescTimestamp is the schema descriptor for timestamp field.
	messageDescTimestamp := messageFields[1].Descriptor()
	// message.DefaultTimestamp holds the default value on creation for the timestamp field.
	message.DefaultTimestamp = messageDescTimestamp.Default.(func() time.Time)
	professorFields := schema.Professor{}.Fields()
	_ = professorFields
	// professorDescName is the schema descriptor for name field.
	professorDescName := professorFields[0].Descriptor()
	// professor.NameValidator is a validator for the "name" field. It is called by the builders before save.
	professor.NameValidator = professorDescName.Validators[0].(func(string) error)
	// professorDescHireDate is the schema descriptor for hire_date field.
	professorDescHireDate := professorFields[1].Descriptor()
	// professor.DefaultHireDate holds the default value on creation for the hire_date field.
	professor.DefaultHireDate = professorDescHireDate.Default.(func() time.Time)
	// professorDescPassword is the schema descriptor for password field.
	professorDescPassword := professorFields[2].Descriptor()
	// professor.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	professor.PasswordValidator = professorDescPassword.Validators[0].(func(string) error)
	studentFields := schema.Student{}.Fields()
	_ = studentFields
	// studentDescName is the schema descriptor for name field.
	studentDescName := studentFields[0].Descriptor()
	// student.DefaultName holds the default value on creation for the name field.
	student.DefaultName = studentDescName.Default.(string)
	// student.NameValidator is a validator for the "name" field. It is called by the builders before save.
	student.NameValidator = studentDescName.Validators[0].(func(string) error)
	// studentDescEnrollmentDate is the schema descriptor for enrollment_date field.
	studentDescEnrollmentDate := studentFields[1].Descriptor()
	// student.DefaultEnrollmentDate holds the default value on creation for the enrollment_date field.
	student.DefaultEnrollmentDate = studentDescEnrollmentDate.Default.(func() time.Time)
	// studentDescPassword is the schema descriptor for password field.
	studentDescPassword := studentFields[2].Descriptor()
	// student.DefaultPassword holds the default value on creation for the password field.
	student.DefaultPassword = studentDescPassword.Default.(string)
	// studentDescNationalNumber is the schema descriptor for national_number field.
	studentDescNationalNumber := studentFields[3].Descriptor()
	// student.DefaultNationalNumber holds the default value on creation for the national_number field.
	student.DefaultNationalNumber = studentDescNationalNumber.Default.(string)
	// studentDescPhoneNumber is the schema descriptor for phone_number field.
	studentDescPhoneNumber := studentFields[4].Descriptor()
	// student.DefaultPhoneNumber holds the default value on creation for the phone_number field.
	student.DefaultPhoneNumber = studentDescPhoneNumber.Default.(string)
	// studentDescHomeLocation is the schema descriptor for home_location field.
	studentDescHomeLocation := studentFields[5].Descriptor()
	// student.DefaultHomeLocation holds the default value on creation for the home_location field.
	student.DefaultHomeLocation = studentDescHomeLocation.Default.(string)
	// studentDescEnycrptionKey is the schema descriptor for enycrption_key field.
	studentDescEnycrptionKey := studentFields[6].Descriptor()
	// student.DefaultEnycrptionKey holds the default value on creation for the enycrption_key field.
	student.DefaultEnycrptionKey = studentDescEnycrptionKey.Default.(string)
	universityFields := schema.University{}.Fields()
	_ = universityFields
	// universityDescName is the schema descriptor for name field.
	universityDescName := universityFields[0].Descriptor()
	// university.NameValidator is a validator for the "name" field. It is called by the builders before save.
	university.NameValidator = universityDescName.Validators[0].(func(string) error)
	// universityDescLocation is the schema descriptor for location field.
	universityDescLocation := universityFields[1].Descriptor()
	// university.LocationValidator is a validator for the "location" field. It is called by the builders before save.
	university.LocationValidator = universityDescLocation.Validators[0].(func(string) error)
	// universityDescEstablishedDate is the schema descriptor for established_date field.
	universityDescEstablishedDate := universityFields[2].Descriptor()
	// university.DefaultEstablishedDate holds the default value on creation for the established_date field.
	university.DefaultEstablishedDate = universityDescEstablishedDate.Default.(func() time.Time)
}
