// Code generated by ent, DO NOT EDIT.

package ent

import (
	"awesomeProject1/ent/university"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UniversityCreate is the builder for creating a University entity.
type UniversityCreate struct {
	config
	mutation *UniversityMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (uc *UniversityCreate) SetName(s string) *UniversityCreate {
	uc.mutation.SetName(s)
	return uc
}

// SetLocation sets the "location" field.
func (uc *UniversityCreate) SetLocation(s string) *UniversityCreate {
	uc.mutation.SetLocation(s)
	return uc
}

// SetEstablishedDate sets the "established_date" field.
func (uc *UniversityCreate) SetEstablishedDate(t time.Time) *UniversityCreate {
	uc.mutation.SetEstablishedDate(t)
	return uc
}

// SetNillableEstablishedDate sets the "established_date" field if the given value is not nil.
func (uc *UniversityCreate) SetNillableEstablishedDate(t *time.Time) *UniversityCreate {
	if t != nil {
		uc.SetEstablishedDate(*t)
	}
	return uc
}

// Mutation returns the UniversityMutation object of the builder.
func (uc *UniversityCreate) Mutation() *UniversityMutation {
	return uc.mutation
}

// Save creates the University in the database.
func (uc *UniversityCreate) Save(ctx context.Context) (*University, error) {
	uc.defaults()
	return withHooks(ctx, uc.sqlSave, uc.mutation, uc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UniversityCreate) SaveX(ctx context.Context) *University {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uc *UniversityCreate) Exec(ctx context.Context) error {
	_, err := uc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uc *UniversityCreate) ExecX(ctx context.Context) {
	if err := uc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uc *UniversityCreate) defaults() {
	if _, ok := uc.mutation.EstablishedDate(); !ok {
		v := university.DefaultEstablishedDate()
		uc.mutation.SetEstablishedDate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uc *UniversityCreate) check() error {
	if _, ok := uc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "University.name"`)}
	}
	if v, ok := uc.mutation.Name(); ok {
		if err := university.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "University.name": %w`, err)}
		}
	}
	if _, ok := uc.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "University.location"`)}
	}
	if v, ok := uc.mutation.Location(); ok {
		if err := university.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "University.location": %w`, err)}
		}
	}
	if _, ok := uc.mutation.EstablishedDate(); !ok {
		return &ValidationError{Name: "established_date", err: errors.New(`ent: missing required field "University.established_date"`)}
	}
	return nil
}

func (uc *UniversityCreate) sqlSave(ctx context.Context) (*University, error) {
	if err := uc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uc.mutation.id = &_node.ID
	uc.mutation.done = true
	return _node, nil
}

func (uc *UniversityCreate) createSpec() (*University, *sqlgraph.CreateSpec) {
	var (
		_node = &University{config: uc.config}
		_spec = sqlgraph.NewCreateSpec(university.Table, sqlgraph.NewFieldSpec(university.FieldID, field.TypeInt))
	)
	if value, ok := uc.mutation.Name(); ok {
		_spec.SetField(university.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := uc.mutation.Location(); ok {
		_spec.SetField(university.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := uc.mutation.EstablishedDate(); ok {
		_spec.SetField(university.FieldEstablishedDate, field.TypeTime, value)
		_node.EstablishedDate = value
	}
	return _node, _spec
}

// UniversityCreateBulk is the builder for creating many University entities in bulk.
type UniversityCreateBulk struct {
	config
	err      error
	builders []*UniversityCreate
}

// Save creates the University entities in the database.
func (ucb *UniversityCreateBulk) Save(ctx context.Context) ([]*University, error) {
	if ucb.err != nil {
		return nil, ucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ucb.builders))
	nodes := make([]*University, len(ucb.builders))
	mutators := make([]Mutator, len(ucb.builders))
	for i := range ucb.builders {
		func(i int, root context.Context) {
			builder := ucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UniversityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucb *UniversityCreateBulk) SaveX(ctx context.Context) []*University {
	v, err := ucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucb *UniversityCreateBulk) Exec(ctx context.Context) error {
	_, err := ucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucb *UniversityCreateBulk) ExecX(ctx context.Context) {
	if err := ucb.Exec(ctx); err != nil {
		panic(err)
	}
}
