// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chat is the predicate function for chat builders.
type Chat func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Professor is the predicate function for professor builders.
type Professor func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)

// University is the predicate function for university builders.
type University func(*sql.Selector)
